version: '3.8'

services:
  bunker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bunker-password-manager
    volumes:
      # Mount vaults directory for persistent storage
      - ./vaults:/app/vaults
      # Mount SSH keys for Git operations (read-only)
      - ~/.ssh:/home/bunker/.ssh:ro
      # Mount GPG keys if using GPG encryption
      - ~/.gnupg:/home/bunker/.gnupg:ro
    environment:
      - RUST_LOG=info
      - BUNKER_VAULT_PATH=/app/vaults
      - BUNKER_SESSION_TIMEOUT=86400
      - BUNKER_CLIPBOARD_TIMEOUT=45
    working_dir: /app
    # Use host networking for clipboard access (Linux/macOS)
    network_mode: host
    # Restart policy for production
    restart: unless-stopped
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    # Health check
    healthcheck:
      test: ["CMD", "bunker", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Labels for organization
    labels:
      - "com.bunker.description=Secure Password Manager"
      - "com.bunker.version=1.0.0"
      - "com.bunker.maintainer=your-email@example.com"

  # Optional: Development service with hot reload
  bunker-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: bunker-dev
    volumes:
      - ./vaults:/app/vaults
      - ./src:/app/src
      - ~/.ssh:/home/bunker/.ssh:ro
    environment:
      - RUST_LOG=debug
      - BUNKER_VAULT_PATH=/app/vaults
    working_dir: /app
    command: ["sh", "-c", "cargo watch -x run"]
    profiles:
      - dev

volumes:
  bunker-vaults:
    driver: local

networks:
  default:
    name: bunker-network
    driver: bridge
